name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  HOME: /root

permissions:
  contents: read
  pages: write
  id-token: write 

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  playwright-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.49.0-noble
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Run Playwright tests
      run: npm run test:ci

    - name: Setup GitHub Pages
      if: ${{ !cancelled() }}
      uses: actions/configure-pages@v5

    - name: Upload Artifact to GitHub Pages
      if: ${{ !cancelled() }}
      uses: actions/upload-pages-artifact@v3
      with:
        path: playwright-report/
        retention-days: 30

    - name: Deploy to GitHub Pages
      if: ${{ !cancelled() }}
      id: deployment
      uses: actions/deploy-pages@v4
